EJ3 = ej3

all: a b c d e f g h

a: $(EJ3)a.s
	gcc -o $(EJ3)a.out -Wall -Werror -g $(EJ3)a.s

b: $(EJ3)b.s
	gcc -o $(EJ3)b.out -Wall -Werror -g $(EJ3)b.s

c: $(EJ3)c.s
	gcc -o $(EJ3)c.out -Wall -Werror -g $(EJ3)c.s

d: $(EJ3)d.s
	gcc -o $(EJ3)d.out -Wall -Werror -g $(EJ3)d.s

e: $(EJ3)e.s
	gcc -o $(EJ3)e.out -Wall -Werror -g $(EJ3)e.s

f: $(EJ3)f.s
	gcc -o $(EJ3)f.out -Wall -Werror -g $(EJ3)f.s

g: $(EJ3)g.s
	gcc -o $(EJ3)g.out -Wall -Werror -g $(EJ3)g.s

h: $(EJ3)h.s
	gcc -o $(EJ3)h.out -Wall -Werror -g $(EJ3)h.s

clean:
	rm *.out